# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='ODB\xca\xfd\xbe\xdd\xd7\xd4\xb6\xaf\xcc\xe1\xc8\xa1\xb3\xcc\xd0\xf2', kernelModule='Case_16_4', kernelFunction='ODBDataExtraction', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='\xb2\xce\xca\xfd', layout='LAYOUT_FILL_X')
RsgFileTextField(p='GroupBox_1', ncols=12, labelText='\xce\xc4\xbc\xfe\xc3\xfb:', keyword='OdbPath', default='myJob.odb', patterns='All files (*)')
RsgTextField(p='GroupBox_1', fieldType='Integer', ncols=12, labelText='\xbd\xda\xb5\xe3\xba\xc5:', keyword='ElementNumber', default='644')
RsgSeparator(p='GroupBox_1')
RsgGroupBox(name='GroupBox_8', p='DialogBox', text='', layout='0')
RsgIcon(p='GroupBox_8', fileName=r'DataExtraction.png')
dialogBox.show()